#!/usr/bin/env python3
"""Render the human-readable plan and the dashboard data from the canonical plan.json.

plan.json is the single source of truth (edited as each batch is built). This script
regenerates:
  - content-plan/plan-rows.js : window.PLAN_ROWS = [...] for content-plan.html (works on file:// too)
  - content-plan/plan.md      : readable per-pillar listing the publishing worker reads

Run after every plan batch.
"""
import json, os
from collections import defaultdict

PLAN = "content-plan/plan.json"
ROWS_JS = "content-plan/plan-rows.js"
PLAN_MD = "content-plan/plan.md"
TOTAL_TARGET = 1085

def main():
    plan = json.load(open(PLAN, encoding="utf-8"))

    # plan-rows.js for the dashboard
    js = "window.PLAN_ROWS = " + json.dumps(plan, ensure_ascii=False, indent=2) + ";\n"
    js += f"window.PLAN_TOTAL_TARGET = {TOTAL_TARGET};\n"
    open(ROWS_JS, "w", encoding="utf-8").write(js)

    # plan.md, grouped by pillar then role
    by_pillar = defaultdict(list)
    for r in plan:
        by_pillar[r.get("pillar", "Unassigned")].append(r)
    lines = ["# The Pearson Co. — 12-month content plan",
             "",
             f"{len(plan)} of ~{TOTAL_TARGET} records built. Canonical data: plan.json. This file is generated by scripts/render_plan.py; do not hand-edit.",
             ""]
    role_order = {"pillar": 0, "money": 1, "authority": 2}
    for pillar in sorted(by_pillar):
        recs = sorted(by_pillar[pillar], key=lambda r: (role_order.get(r.get("role"), 9), r.get("title", "")))
        lines.append(f"## {pillar}  ({len(recs)})")
        lines.append("")
        for r in recs:
            seq = r.get("seq")
            seq_s = f"seq {seq}" if seq is not None else "seq -"
            ad = " · AD-LANDING" if r.get("is_ad_landing") else ""
            lines.append(f"- **{r.get('title','(untitled)')}**  ({seq_s} · {r.get('role')} · {r.get('content_type')} · {r.get('target_market')}{ad})")
            lines.append(f"  - slug: `/{('services' if r.get('role') in ('pillar','money') else 'blog')}/{r.get('url_slug')}.html`")
            kw = r.get("primary_keyword", "")
            vol = r.get("primary_volume", "")
            kd = r.get("primary_kd", "")
            lines.append(f"  - primary: \"{kw}\" (vol {vol}, KD {kd}, {r.get('intent')})")
            if r.get("secondary_keywords"):
                lines.append(f"  - secondary: {', '.join(r['secondary_keywords'])}")
            il = r.get("internal_links", {})
            if il:
                lines.append(f"  - links up: {', '.join(il.get('up', [])) or '-'} | lateral: {', '.join(il.get('lateral', [])) or '-'}")
            lines.append("")
    open(PLAN_MD, "w", encoding="utf-8").write("\n".join(lines))
    print(f"render_plan: {len(plan)} records -> plan-rows.js + plan.md across {len(by_pillar)} pillars.")

if __name__ == "__main__":
    main()
